---
- name: Install dependencies of ruby
  become: yes
  yum:
    name: "{{ dependencies }}"
    state: latest
    lock_timeout: 180
  vars:
    dependencies:
      - openssl-devel
      - sqlite-devel
      - gcc
      - gcc-c++
      - readline-devel
      - mysql
      - mysql-devel
      - libselinux-python

- name: Install rbenv
  git:
    repo: "{{ rbenv_download_url }}"
    dest: /usr/local/rbenv
  when: not ansible_check_mode

- name: Edit bashrc
  template:
    src: roles/ruby/templates/rbenv_system.sh.j2
    dest: /etc/profile.d/rbenv.sh
    owner: ec2-user
    group: ec2-user

- name: Install ruby-build
  git:
    repo: "{{ ruby_build_download_url }}"
    dest: /usr/local/rbenv/plugins/ruby-build
  when: not ansible_check_mode

- name: Install Ruby
  shell: bash -lc "rbenv install -s {{ ruby_version }}"

- name: Set default Ruby version
  shell: bash -lc "rbenv global {{ ruby_version }} && rbenv rehash"

- name: Install bundler and so on
  shell: bash -lc "gem install {{ item }}"
  with_items:
    - rbenv-rehash
    - bundler -v "{{ bundler_version }}"

- name: Install Rails
  shell: bash -lc "gem install rails -v 5.2.4.2"
